<?php
/**
 * @category Mage
 * @package magento2
 * @author Flagbit Magento Team <magento@flagbit.de>
 * @copyright Copyright (c) 2015 Flagbit GmbH & Co. KG
 * @license GPL
 * @link http://www.flagbit.de
 */
?>
<td class="value">
    <?php foreach ($this->getLinks() as $id => $link): ?>
        <button type="button" id="export-<?php echo $id; ?>" onclick="window.location='<?php echo $link['url'] ?>'">
            <?php echo __($link['label']) ?>
        </button>
    <?php endforeach; ?>
</td>
